/**
 * The stylesheet is a golden fixture, compared byte for byte.
 *
 * The CSS is generated from the design tokens the paginated formats read as
 * well, and this fixture is what proves the generated stylesheet is the one
 * intended, down to the byte. A change here is either a deliberate design
 * change, with the fixture regenerated by running this file with `-u` and
 * reviewed in the same change, or a regression in the generator.
 */

import { it, expect } from "vitest"
import { siteStyles } from "../src/index.js"

it("emits the stylesheet byte for byte", async () => {
  await expect(siteStyles).toMatchFileSnapshot("./__fixtures__/site.css")
})
